Repository RedHatQE/openshift-day2-configurator, pull requests merged in 2024-05, with the labels that each got.

#21 Add more LDAP resources
  .github/in-solidarity.yml
  day2_configuration.example.yaml
  docs/developer-guide.MD
  openshift_day2_configurator/configurators/ldap.py
  openshift_day2_configurator/tests/conftest.py
  openshift_day2_configurator/tests/test_resources.py
  openshift_day2_configurator/utils/resources.py
  poetry.lock
  pyproject.toml
Labels: branch-main, verified, size/XL, can-be-merged, approved-myakove, JIRA:MSINTEROP-953

#25 Add ocp client, mypy and typing fixes, use ocp-wrapper to create ldap-secret
  .pre-commit-config.yaml
  docs/developer-guide.MD
  openshift_day2_configurator/cli.py
  openshift_day2_configurator/configuration/configurations.py
  openshift_day2_configurator/configurators/executor.py
  openshift_day2_configurator/configurators/ldap.py
  openshift_day2_configurator/configurators/mappings.py
  openshift_day2_configurator/tests/test_day2_config_checks.py
  openshift_day2_configurator/tests/test_execute_configurators.py
  openshift_day2_configurator/tests/test_resources.py
  openshift_day2_configurator/utils/general.py
  openshift_day2_configurator/utils/resources.py
  pyproject.toml
Labels: branch-main, verified, size/XL, can-be-merged, approved-myakove, JIRA:MSINTEROP-977

#27 Add documentation for tests
  docs/developer-guide.MD
Labels: branch-main, verified, size/XS, can-be-merged, approved-rnetser
